#!/usr/bin/env python3
"""Stage 2: back-fill missing generalDescription translations from Documents TSV.

Reads:
  - /tmp/identifier_map.tsv  (value=identifier  resource_id)
  - /tmp/gendesc_state.tsv   (resource_id  lang)
  - data/Documents2024-12-13.tsv  (HE col 4, DE col 5, EN col 6, identifier col 2)

Writes:
  - /tmp/stage2_inserts.sql  (INSERTs to add missing lang values)

Rules:
  - For each TSV row with identifier matching a resource, check what langs
    are already present in generalDescription (property_id=3502).
  - For each of he/de/en not present, insert a new value row with the
    corresponding TSV column.
  - Skip empty TSV cells.
  - Skip placeholder strings like "AI translation pending", "n/a", etc.
"""
import csv
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DOCS_TSV = REPO / "data" / "Documents2024-12-13.tsv"

IDENT_MAP_PATH = Path("/tmp/identifier_map.tsv")
STATE_PATH = Path("/tmp/gendesc_state.tsv")
OUT_SQL = Path("/tmp/stage2_inserts.sql")

PROPERTY_ID_GENDESC = 3502

# Build identifier → resource_id
identifier_to_rid = {}
with open(IDENT_MAP_PATH) as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            continue
        ident, rid = parts
        ident = ident.strip()
        if ident == "" or ident == "NULL":
            continue
        identifier_to_rid[ident] = int(rid)

# Existing generalDescription langs per resource
existing_langs = defaultdict(set)
with open(STATE_PATH) as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t")
        rid = int(parts[0])
        lang = parts[1] if len(parts) > 1 else ""
        existing_langs[rid].add(lang.lower())


def sql_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "''")


def is_meaningful(s: str) -> bool:
    if not s:
        return False
    s = s.strip()
    if len(s) < 3:
        return False
    low = s.lower()
    # Discard obvious empty/placeholder text
    bad = {"n/a", "na", "none", "null", "tbd", "pending", "-"}
    return low not in bad


added = {"he": 0, "de": 0, "en": 0}
matched_rows = 0
unmatched_ids = 0
inserts = []

with open(DOCS_TSV, newline="") as f:
    reader = csv.reader(f, delimiter="\t", quoting=csv.QUOTE_NONE)
    header = next(reader)
    # Sanity: col indices (0-based) are: 1=item_id, 3=item_description (HE),
    # 4=german_translation, 5=english_translation
    for row in reader:
        if len(row) < 7:
            continue
        ident = row[1].strip()
        if not ident:
            continue
        rid = identifier_to_rid.get(ident)
        if not rid:
            unmatched_ids += 1
            continue
        matched_rows += 1
        present = existing_langs.get(rid, set())
        candidates = [
            ("he", row[3]),
            ("de", row[4]),
            ("en", row[5]),
        ]
        for lang, text in candidates:
            if not is_meaningful(text):
                continue
            if lang in present:
                continue
            text = text.strip()
            inserts.append(
                f"INSERT INTO value (resource_id, property_id, type, lang, value, is_public) "
                f"VALUES ({rid}, {PROPERTY_ID_GENDESC}, 'literal', '{lang}', '{sql_escape(text)}', 1);"
            )
            added[lang] += 1
            # Mark as added so subsequent rows on same rid don't duplicate
            present.add(lang)
        existing_langs[rid] = present

with open(OUT_SQL, "w") as f:
    f.write("-- Stage 2: back-fill generalDescription translations\n")
    f.write("-- Generated by stage2_generaldescription.py\n")
    f.write("START TRANSACTION;\n")
    for line in inserts:
        f.write(line + "\n")
    f.write("COMMIT;\n")

print(f"Matched TSV rows:       {matched_rows}")
print(f"Unmatched identifiers:  {unmatched_ids}")
print(f"INSERTs by lang: {added}")
print(f"Total INSERTs:   {sum(added.values())}")
print(f"Wrote: {OUT_SQL}")
